// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: My_Watch

#include "ui.h"

void ui_Main_screen_init(void)
{
    lv_obj_t *ui_Main = lv_obj_create(NULL);

    lv_obj_t *arc = lv_arc_create(ui_Main);
    lv_obj_set_width(arc, 480);
    lv_obj_set_height(arc, 480);
    lv_obj_set_style_arc_width(arc, 30, LV_PART_MAIN);
    lv_obj_set_style_arc_width(arc, 30, LV_PART_INDICATOR);

    lv_obj_t *btn = lv_btn_create(ui_Main);
    lv_obj_align(btn, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_height(btn, 50);

    lv_obj_t *ui_Main_Label = lv_label_create(btn);
    lv_obj_set_width(ui_Main_Label, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Main_Label, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Main_Label, 0);
    lv_obj_set_y(ui_Main_Label, 0);
    lv_obj_set_align(ui_Main_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Main_Label, "Main Label");
    //lv_obj_set_style_text_color(ui_Main_Label, lv_color_black(), LV_PART_MAIN);

    lv_scr_load(ui_Main);
}
